### ISSUE TITLE
到这边出错，是什么问题

### ISSUE THREAD

**Issue by sellertool** [xiadd/pastebin-worker#10]
✘ [ERROR] ParseError: A request to the Cloudflare API (/accounts/516d0a360ccdea88dd79e9cf5d2bc3aa/workers/services/pastebin-worker) failed.
      at throwFetchError (/home/runner/work/pastebin-worker/pastebin-worker/node_modules/wrangler/wrangler-dist/cli.js:121134:17)
      at fetchResult (/home/runner/work/pastebin-worker/pastebin-worker/node_modules/wrangler/wrangler-dist/cli.js:121087:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/sellertool/pastebin-worker/actions/runs/8001366957/job/21853029687#step:7:11)5:5)
      at async deploy (/home/runner/work/pastebin-worker/pastebin-worker/node_modules/wrangler/wrangler-dist/cli.js:147720:31)
      at async Object.deployHandler [as handler] (/home/runner/work/pastebin-worker/pastebin-worker/node_modules/wrangler/wrangler-dist/cli.js:138267:3) {
    text: 'A request to the Cloudflare API (/accounts/516d0a360ccdea88dd79e9cf5d2bc3aa/workers/services/pastebin-worker) failed.',
    notes: [ { text: 'Authentication error [code: [10](https://github.com/sellertool/pastebin-worker/actions/runs/8001366957/job/21853029687#step:7:12)000]' } ],
    location: undefined,
    kind: 'error',
    code: 10000
  }
Error: 🚨 Action failed

**Comment by xiadd** [comment]
> text: 'A request to the Cloudflare API (/accounts/516d0a360ccdea88dd79e9cf5d2bc3aa/workers/services/pastebin-worker) failed.',

account_id 改成你自己的，这是我的account_id

**Comment by sellertool** [comment]
现在到 publish出错
11s
Run cloudflare/wrangler-action@3.0.0
📥 Installing Wrangler
📌 No Wrangler commands were provided, executing default deployment.
Error: 🚨 Action failed

**Comment by xiadd** [comment]
r2 bucket和kv namespace都创建好了吗？
